# Generated by Django 5.0.1 on 2024-02-12 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_content', models.TextField()),
                ('create_dt', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 12, 11, 5, 23, 305086, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('create_dt', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 12, 11, 5, 23, 303727, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
