# Generated by Django 5.0.1 on 2024-02-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200)),
                ('book_content', models.TextField()),
                ('create_dt', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='BookContent',
        ),
        migrations.DeleteModel(
            name='BookTitle',
        ),
    ]
