# Generated by Django 5.0.1 on 2024-02-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_book_delete_bookcontent_delete_booktitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
    ]
