# Generated by Django 5.0.1 on 2024-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_book_content_book_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
