# Generated by Django 5.0.1 on 2024-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modify_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
